title:             Harshit Bansal
email:             harshit.bansalec@gmail.com
description:       Software Developer-Deep Learning Enthusiast
author:            Harshit Bansal
baseurl:           ""
url:               "http://harshitbansal05.github.io"

# Social Profiles
twitter_username:  _harshit_bansal
github_username:   harshitbansal05
linkedin_username: harshit-bansal-b21b51141
facebook_username: harshit.bansal.560

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
